### ISSUE TITLE
Issue with running plugin locally

### ISSUE THREAD

**Issue by KevinGutowski** [brianlovin/figma-export-zip#7]
![CleanShot 2021-06-21 at 23 12 04](https://user-images.githubusercontent.com/4199296/122873028-24ffff80-d2e6-11eb-98e4-1cb957f09dc8.png)

I’m getting this error when trying to build and run the plugin locally (trying to write something that downloads assets in folders so I figured I would start with trying to get yours to run!). 

Any pointers on fixing this? My googling hasn’t really led to me to a helpful answer.

**Comment by brianlovin** [comment]
Hmmm it's very likely that some dependency update has broken the way the code should be written. Unfortunately I don't have time to dig into this, but the `Unexpected token` tends to point to some line above it not closing correctly (missing bracket or something?)

**Comment by KevinGutowski** [comment]
Gotcha! I'll poke at it some more and if I find a fix I'll share here.
